[debug] [2020-04-15T00:19:06.874Z] ----------------------------------------------------------------------
[debug] [2020-04-15T00:19:06.880Z] Command:       /usr/local/bin/node /Users/ThisFolderIsGreat/Google Drive/GI04-P20-MEDELLIN/ST0256 - ANALISIS NUMERICO/Proyecto/numerical-analysis-website/node_modules/.bin/firebase deploy
[debug] [2020-04-15T00:19:06.881Z] CLI Version:   7.15.1
[debug] [2020-04-15T00:19:06.881Z] Platform:      darwin
[debug] [2020-04-15T00:19:06.881Z] Node Version:  v10.16.3
[debug] [2020-04-15T00:19:06.883Z] Time:          Tue Apr 14 2020 19:19:06 GMT-0500 (Colombia Standard Time)
[debug] [2020-04-15T00:19:06.883Z] ----------------------------------------------------------------------
[debug] [2020-04-15T00:19:06.883Z] 
[debug] [2020-04-15T00:19:06.916Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-15T00:19:06.917Z] > authorizing via signed-in user
[debug] [2020-04-15T00:19:06.918Z] [iam] checking project peanut-numerical-analysis for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2020-04-15T00:19:06.921Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-04-15T00:19:06.922Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-04-15T00:19:20.937Z] <<< HTTP RESPONSE 200
[debug] [2020-04-15T00:19:20.962Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/peanut-numerical-analysis:testIamPermissions  

[debug] [2020-04-15T00:19:29.999Z] <<< HTTP RESPONSE 200
[debug] [2020-04-15T00:19:30.001Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/peanut-numerical-analysis  
 
[debug] [2020-04-15T00:19:40.112Z] Server Error. connect ETIMEDOUT 172.217.30.202:443
[debug] [2020-04-15T00:19:43.058Z] FirebaseError: Server Error. connect ETIMEDOUT 172.217.30.202:443
    at Request._callback (/Users/ThisFolderIsGreat/Google Drive/GI04-P20-MEDELLIN/ST0256 - ANALISIS NUMERICO/Proyecto/numerical-analysis-website/node_modules/firebase-tools/lib/api.js:30:31)
    at self.callback (/Users/ThisFolderIsGreat/Google Drive/GI04-P20-MEDELLIN/ST0256 - ANALISIS NUMERICO/Proyecto/numerical-analysis-website/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.onRequestError (/Users/ThisFolderIsGreat/Google Drive/GI04-P20-MEDELLIN/ST0256 - ANALISIS NUMERICO/Proyecto/numerical-analysis-website/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: Failed to get Firebase project peanut-numerical-analysis. Please make sure the project exists and your account has permission to access it.
